### ISSUE TITLE
SFTP logging

### ISSUE THREAD

**Issue by 2LINKIT** [yakworks/docker-sftp#7]
how can I get detailed logs when people upload/download files to the FTP server including timestamp (when), who, what. I need to have the documentation in place

Preferable I would like any events to be redirected to stdout so it will be send to Azure Loganalytics.
Alternative a method on how to forward syslogs to another host for collection

Pls note: I'm a newbie in this :-)

**Comment by basejump** [comment]
if you figured out a good way to do this, please post and will add to README
